/*
  Mosque Manager Web V2 - GitHub Pages client
  ضع رابط Apps Script Web App هنا بعد النشر:
*/
const API_URL = 'PASTE_APPS_SCRIPT_EXEC_URL_HERE';
const APP_VERSION = 'web-v2.0';

const state = { user:null, data:null, page:'dashboard', qr:null, currentFollowupRows:[] };
const $ = s => document.querySelector(s);
const $$ = s => Array.from(document.querySelectorAll(s));
const today = () => new Date().toISOString().slice(0,10);
const nowTime = () => new Date().toLocaleTimeString('ar-SY',{hour:'2-digit',minute:'2-digit'});
const uid = () => String(Date.now()) + Math.floor(Math.random()*1000);
const esc = v => String(v ?? '').replace(/[&<>"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));

async function api(action, data={}){
  if(API_URL.includes('PASTE_')) throw new Error('لم يتم وضع رابط Apps Script داخل app.js');
  const res = await fetch(API_URL, {method:'POST', body:JSON.stringify({action, data, token:localStorage.mm_token||''})});
  const txt = await res.text();
  let json; try{ json=JSON.parse(txt); }catch(e){ throw new Error('رد السيرفر غير صالح: '+txt.slice(0,140)); }
  if(!json.ok) throw new Error(json.error || 'حدث خطأ');
  if(json.token) localStorage.mm_token=json.token;
  return json.data;
}
function toast(msg, bad=false){ let t=$('.toast'); if(!t){t=document.createElement('div');t.className='toast';document.body.appendChild(t)} t.textContent=msg;t.style.background=bad?'#c0392b':'#0f6b4f';t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2800); }
async function boot(){ renderLogin(); try{ const me=await api('me'); state.user=me.user; await load(); }catch(e){} }
async function load(){ state.data = await api('bootstrap'); renderApp(); }
function renderLogin(){ $('#app').innerHTML = `<div class="login-page"><div class="login-card"><h1>منصة الإدارة الذكية</h1><p>تسجيل الدخول إلى نظام المسجد والمعهد</p><div class="field"><label>اسم المستخدم</label><input id="u" value="admin"></div><br><div class="field"><label>كلمة المرور</label><input id="p" type="password" value="admin"></div><br><button class="btn" style="width:100%" onclick="login()">دخول</button></div></div>`; }
async function login(){ try{ const data=await api('login',{username:$('#u').value.trim(),password:$('#p').value}); state.user=data.user; await load(); }catch(e){toast(e.message,true)} }
function logout(){ localStorage.removeItem('mm_token'); state.user=null; state.data=null; renderLogin(); }
function isAdmin(){return state.user?.role==='admin'} function isTeacher(){return state.user?.role==='teacher'} function isSupervisor(){return state.user?.role==='supervisor'}
function teacherHalaqaIds(){ if(!isTeacher()) return null; const tid=state.user.teacher_id; return state.data.halaqat.filter(h=>String(h.teacher_id)===String(tid)).map(h=>String(h.id)); }
function visibleStudents(){ let rows=state.data.students||[]; if(isTeacher()){ const hs=teacherHalaqaIds(); rows=rows.filter(s=>hs.includes(String(s.halaqa_id))); } return rows; }
const navItems = [
 ['dashboard','لوحة التحكم','🏠'],['students','الطلاب','👥'],['search','البحث','🔎'],['attendance','الحضور','✅'],['late','المتأخرون','⏰'],['followups','المتابعة','📖'],['reports','التقارير','🖨️'],['teachers','المدرسون','👨‍🏫'],['halaqat','الحلقات','🕌'],['events','الفعاليات','🏆'],['users','المستخدمون','🔐'],['settings','الإعدادات','⚙️']
];
function allowedPage(p){ if(isAdmin()) return true; if(isSupervisor()) return ['dashboard','search','reports','followups','late'].includes(p); if(isTeacher()) return ['dashboard','search','attendance','late','followups'].includes(p); return false; }
function renderApp(){ const nav=navItems.filter(([p])=>allowedPage(p)).map(([p,t,i])=>`<button class="${state.page===p?'active':''}" onclick="go('${p}')">${i} ${t}</button>`).join(''); $('#app').innerHTML=`<div class="app-shell"><aside class="sidebar"><div class="brand"><div class="logo">🕌</div><div><h1>${esc(state.data.settings.institution_name||'منصة الإدارة الذكية')}</h1><small>${esc(state.user.role)}</small></div></div><nav class="nav">${nav}<button onclick="logout()">🚪 خروج</button></nav></aside><main class="main"><div class="topbar"><h2 class="page-title">${pageTitle()}</h2><div class="userbox"><b>${esc(state.user.username)}</b><span class="badge">${roleName(state.user.role)}</span></div></div><div id="view"></div></main></div>`; renderPage(); }
function go(p){ state.page=p; renderApp(); }
function pageTitle(){ return Object.fromEntries(navItems.map(x=>[x[0],x[1]]))[state.page]||'' } function roleName(r){return {admin:'إدارة',teacher:'أستاذ',supervisor:'مشرف'}[r]||r}
function renderPage(){ const v=$('#view'); const pages={dashboard,students,search,attendance,late,followups,reports,teachers,halaqat,events,users,settings}; (pages[state.page]||dashboard)(v); }
function dashboard(v){ const students=visibleStudents(); const att=(state.data.attendance||[]).filter(a=>a.date===today()); const ids=new Set(students.map(s=>String(s.id))); const todayAtt=att.filter(a=>ids.has(String(a.student_id)) && a.status==='حاضر').length; const todayAbs=att.filter(a=>ids.has(String(a.student_id)) && (a.status||'').includes('غائب')).length; v.innerHTML=`<div class="grid"><div class="card stat"><div><span>${isTeacher()?'طلاب حلقتي':'إجمالي الطلاب'}</span><b>${students.length}</b></div>👥</div><div class="card stat"><div><span>الحاضرون اليوم</span><b>${todayAtt}</b></div>✅</div><div class="card stat"><div><span>الغائبون اليوم</span><b>${todayAbs}</b></div>❌</div>${!isTeacher()?`<div class="card stat"><div><span>المدرسون</span><b>${state.data.teachers.length}</b></div>👨‍🏫</div>`:''}</div><div class="card section"><h3>تنبيه تشغيل</h3><p>نسخة الويب تعمل عبر Google Apps Script و Google Sheets. لا تحتاج Python أو تشغيل لابتوب كسيرفر بعد النشر.</p></div>`; }
function students(v){ if(!isAdmin()) return search(v); v.innerHTML=`<div class="toolbar"><button class="btn" onclick="studentForm()">إضافة طالب</button><input id="studentQ" placeholder="بحث بالاسم" oninput="studentsTable()"></div><div id="studentsTable"></div>`; studentsTable(); }
function studentsTable(){ const q=($('#studentQ')?.value||'').trim(); const rows=(state.data.students||[]).filter(s=>!q||s.name?.includes(q)); $('#studentsTable').innerHTML=table(['ID','الصورة','الاسم','الحلقة','ولي الأمر','الحالة','إجراءات'],rows.map(s=>[s.id,photo(s.photo_url,46),esc(s.name),halaqaName(s.halaqa_id),waLink(s.guardian_phone,'فتح واتساب'),badge(s.status||'نشط'),`<button class="btn secondary" onclick="studentProfile('${s.id}')">ملف</button> <button class="btn secondary" onclick="qrCard('${s.id}')">بطاقة QR</button> <button class="btn gold" onclick="studentForm('${s.id}')">تعديل</button> <button class="btn danger" onclick="delRow('students','${s.id}')">حذف</button>`])); }
function search(v){ const rows=visibleStudents(); v.innerHTML=`<div class="card"><div class="table-wrap">${table(['اسم الطالب','رقم ولي الأمر','الحالة','ملف'],rows.map(s=>[esc(s.name),esc(s.guardian_phone||''),badge(s.status||'نشط'),`<button class="btn secondary" onclick="studentProfile('${s.id}')">ملف</button>${isAdmin()?` <button class="btn secondary" onclick="qrCard('${s.id}')">بطاقة QR</button>`:''}`]))}</div></div>`; }
function studentForm(id=''){ const s=state.data.students.find(x=>String(x.id)===String(id))||{}; const modal=showModal(`<h3>${id?'تعديل':'إضافة'} طالب</h3><div class="form"><div class="field"><label>ID</label><input id="sid" value="${esc(s.id||nextStudentId())}" ${id?'readonly':''}></div><div class="field"><label>الاسم</label><input id="sname" value="${esc(s.name)}"></div><div class="field"><label>الحلقة</label><select id="shalaqa">${state.data.halaqat.map(h=>`<option value="${h.id}" ${String(h.id)===String(s.halaqa_id)?'selected':''}>${esc(h.name)}</option>`)}</select></div><div class="field"><label>رقم ولي الأمر</label><input id="sguard" value="${esc(s.guardian_phone)}"></div><div class="field"><label>الصف</label><input id="sgrade" value="${esc(s.grade)}"></div><div class="field"><label>الحالة</label><select id="sstatus"><option ${s.status!=='مفصول'?'selected':''}>نشط</option><option ${s.status==='مفصول'?'selected':''}>مفصول</option></select></div><div class="field"><label>صورة الطالب</label><input id="sphoto" type="file" accept="image/*" capture="environment" onchange="previewPhoto(this)"></div><div class="field"><label>معاينة</label><img id="sphotoPreview" class="student-photo" src="${s.photo_url||''}" onerror="this.src=''" /></div><div class="field" style="grid-column:1/-1"><label>ملاحظات</label><textarea id="snotes">${esc(s.notes)}</textarea></div></div><br><button class="btn" onclick="saveStudent('${id}')">حفظ</button>`); }
function nextStudentId(){ const n=Number(state.data.settings.next_student_id||100001); return n||Date.now(); }
function previewPhoto(inp){ const f=inp.files[0]; if(!f) return; const r=new FileReader(); r.onload=()=>$('#sphotoPreview').src=r.result; r.readAsDataURL(f); }
async function saveStudent(oldId){ try{ const photo=$('#sphotoPreview').src.startsWith('data:')?$('#sphotoPreview').src:($('#sphotoPreview').getAttribute('src')||''); const data={id:$('#sid').value.trim(),name:$('#sname').value.trim(),halaqa_id:$('#shalaqa').value,guardian_phone:$('#sguard').value,grade:$('#sgrade').value,status:$('#sstatus').value,notes:$('#snotes').value,photo_data:photo,old_id:oldId}; await api('saveStudent',data); toast('تم حفظ الطالب'); closeModal(); await load(); }catch(e){toast(e.message,true)} }
function studentProfile(id){ const s=state.data.students.find(x=>String(x.id)===String(id)); if(!s) return; const fs=(state.data.followups||[]).filter(f=>String(f.student_id)===String(id)).sort((a,b)=>(b.date||'').localeCompare(a.date||'')); const ev=eventResultsFor(id); showModal(`<div class="profile"><div><img class="student-photo" src="${esc(s.photo_url||'')}" onerror="this.style.display='none'"></div><div><h2>${esc(s.name)}</h2><div class="kv"><div><b>ID</b><br>${esc(s.id)}</div><div><b>الحلقة</b><br>${halaqaName(s.halaqa_id)}</div><div><b>ولي الأمر</b><br>${esc(s.guardian_phone||'')}</div><div><b>الحالة</b><br>${esc(s.status||'نشط')}</div><div><b>الصف</b><br>${esc(s.grade||'')}</div><div><b>ملاحظات</b><br>${esc(s.notes||'')}</div></div></div></div><hr><h3>آخر متابعة</h3>${fs[0]?followupDetails(fs[0]):'<p>لا يوجد متابعة.</p>'}<h3>الفعاليات</h3>${ev.length?table(['الفعالية','نسبة الإنجاز'],ev.map(x=>[esc(x.name),x.percent+'%'])):'<p>لا توجد مشاركات.</p>'}<div class="no-print">${isAdmin()?'<button class="btn" onclick="window.print()">طباعة</button>':''}</div>`); }
function followupDetails(f){ let extra=''; try{ const o=JSON.parse(f.fields_json||'{}'); extra=Object.entries(o).map(([k,v])=>`<div><b>${esc(k)}</b><br>${esc(v)}</div>`).join(''); }catch(e){} return `<div class="kv"><div><b>التاريخ</b><br>${esc(f.date)}</div><div><b>الحالة</b><br>${esc(f.status||'')}</div>${extra}</div>`; }
function attendance(v){ const rows=visibleStudents(); v.innerHTML=`<div class="card"><div class="toolbar"><button class="btn" onclick="openQrScanner('attendance')">فتح قارئ QR</button><input id="manualStudent" placeholder="ID أو اسم الطالب"><button class="btn secondary" onclick="markManualPresent()">تسجيل يدوي حاضر</button><button class="btn gold" onclick="saveAttendanceBulk()">حفظ جماعي</button></div><div class="table-wrap">${table(['الطالب','الحالة'],rows.map(s=>[esc(s.name),`<select data-att="${s.id}"><option value="">اختر</option><option>حاضر</option><option>غائب</option><option>غياب مبرر</option><option>لم يسمع شيئاً</option></select>`]))}</div></div><div id="qrBox"></div>`; }
function markManualPresent(){ const q=$('#manualStudent').value.trim(); const s=visibleStudents().find(x=>String(x.id)===q || (x.name||'').includes(q)); if(!s) return toast('لم يتم العثور على الطالب',true); document.querySelector(`[data-att="${s.id}"]`).value='حاضر'; toast('تم تحديد الطالب حاضر'); }
async function saveAttendanceBulk(){ try{ const rows=$$('[data-att]').map(el=>({student_id:el.dataset.att,status:el.value})).filter(x=>x.status); await api('saveAttendanceBulk',{date:today(),time:nowTime(),rows}); toast('تم حفظ الحضور'); await load(); }catch(e){toast(e.message,true)} }
function openQrScanner(mode,eventId='',slot=''){ const box=$('#qrBox')||document.body.appendChild(document.createElement('div')); box.innerHTML='<div class="card section"><div id="reader" style="max-width:420px"></div><button class="btn secondary" onclick="stopQr()">إغلاق</button></div>'; if(!window.Html5Qrcode) return toast('مكتبة QR غير متاحة',true); state.qr = new Html5Qrcode('reader'); state.qr.start({facingMode:'environment'},{fps:10,qrbox:250}, txt=>handleQr(txt,mode,eventId,slot)).catch(e=>toast('تعذر فتح الكاميرا: '+e,true)); }
function stopQr(){ if(state.qr){ state.qr.stop().catch(()=>{}); state.qr=null; } $('#qrBox') && ($('#qrBox').innerHTML=''); }
function parseStudentCode(txt){ return String(txt).replace('STUDENT:','').trim(); }
async function handleQr(txt,mode,eventId,slot){ const id=parseStudentCode(txt); if(mode==='attendance'){ const el=document.querySelector(`[data-att="${id}"]`); if(el){ el.value='حاضر'; toast('تمت قراءة الطالب'); } else toast('الطالب ليس ضمن الحلقة',true); } if(mode==='event'){ try{ await api('eventCheckin',{event_id:eventId,slot,student_id:id,date:today(),time:nowTime()}); toast('تم تسجيل قراءة الفعالية'); await load(); }catch(e){toast(e.message,true)} } }
function late(v){ const rows=(state.data.late||[]).filter(x=>isAdmin() || visibleStudents().some(s=>String(s.id)===String(x.student_id))); v.innerHTML=`<div class="toolbar"><input id="lateQ" placeholder="اسم أو ID"><button class="btn" onclick="lateManual()">تسجيل متأخر</button>${isAdmin()?'<button class="btn secondary" onclick="window.print()">طباعة</button>':''}</div><div class="table-wrap">${table(['التاريخ','الوقت','الاسم','الحلقة','ID','واتساب'],rows.map(l=>{const s=state.data.students.find(x=>String(x.id)===String(l.student_id))||{};return [l.date,l.time,esc(s.name),halaqaName(s.halaqa_id),l.student_id,waLate(s,l.time)]}))}</div>`; }
async function lateManual(){ const q=$('#lateQ').value.trim(); const s=visibleStudents().find(x=>String(x.id)===q || (x.name||'').includes(q)); if(!s) return toast('لم يتم العثور على الطالب',true); try{ await api('saveLate',{student_id:s.id,date:today(),time:nowTime()}); toast('تم تسجيل التأخير'); await load(); }catch(e){toast(e.message,true)} }
function followups(v){ if(isAdmin()||isSupervisor()) return followupReports(v); const rows=visibleStudents(); v.innerHTML=`<div class="toolbar"><button class="btn gold" onclick="saveFollowupsBulk()">حفظ جماعي</button></div><div class="table-wrap">${table(['الطالب','قرآن','تقييم','حديث','تقييم','متن','تقييم','حالة','ملاحظات'],rows.map(s=>[esc(s.name),`<input data-f="${s.id}:quran">`,`<select data-f="${s.id}:q_eval"><option></option><option>ممتاز</option><option>جيد</option><option>إعادة</option></select>`,`<input data-f="${s.id}:hadith">`,`<select data-f="${s.id}:h_eval"><option></option><option>ممتاز</option><option>جيد</option><option>إعادة</option></select>`,`<input data-f="${s.id}:matn">`,`<select data-f="${s.id}:m_eval"><option></option><option>ممتاز</option><option>جيد</option><option>إعادة</option></select>`,`<select data-f="${s.id}:status"><option></option><option>لم يسمع شيئاً</option><option>غياب مبرر</option></select>`,`<input data-f="${s.id}:notes">`]))}</div>`; }
async function saveFollowupsBulk(){ const map={}; $$('[data-f]').forEach(el=>{const [id,k]=el.dataset.f.split(':'); map[id]=map[id]||{}; map[id][k]=el.value;}); const rows=Object.entries(map).map(([student_id,x])=>({student_id,date:today(),fields_json:JSON.stringify(x),status:x.status||'',teacher_id:state.user.teacher_id||''})).filter(x=>Object.values(JSON.parse(x.fields_json)).some(Boolean)); try{ await api('saveFollowupsBulk',{rows}); toast('تم حفظ المتابعة'); await load(); }catch(e){toast(e.message,true)} }
function followupReports(v){ const hs=state.data.halaqat; v.innerHTML=`<div class="toolbar no-print"><select id="frH"><option value="">كل الحلقات</option>${hs.map(h=>`<option value="${h.id}">${esc(h.name)}</option>`)}</select><input id="frS" placeholder="اسم أو ID الطالب"><input type="date" id="frFrom"><input type="date" id="frTo"><button class="btn" onclick="renderFollowupReport()">عرض</button><button class="btn secondary" onclick="window.print()">طباعة</button></div><div id="followupReport"></div>`; renderFollowupReport(); }
function renderFollowupReport(){ const hid=$('#frH')?.value||''; const q=$('#frS')?.value||''; const from=$('#frFrom')?.value||''; const to=$('#frTo')?.value||''; let fs=state.data.followups||[]; if(from) fs=fs.filter(f=>f.date>=from); if(to) fs=fs.filter(f=>f.date<=to); let students=state.data.students.filter(s=>(!hid||String(s.halaqa_id)===String(hid))&&(!q||String(s.id)===q||s.name?.includes(q))); const ids=new Set(students.map(s=>String(s.id))); fs=fs.filter(f=>ids.has(String(f.student_id))); const title=hid?halaqaName(hid):'كل الحلقات'; $('#followupReport').innerHTML=`<div class="card"><div class="print-head"><h2>جدول متابعة الطلاب</h2><div class="meta"><span>${esc(title)}</span><span>التاريخ: ${today()}</span></div><div class="watermark">🕌</div></div><div class="table-wrap">${table(['التاريخ','اسم الطالب','قرآن','تقييم','حديث','تقييم','متن','تقييم','ملاحظات'],fs.map(f=>{let o={};try{o=JSON.parse(f.fields_json||'{}')}catch(e){} const s=state.data.students.find(x=>String(x.id)===String(f.student_id))||{}; return [f.date,esc(s.name),esc(o.quran||''),stateBadge(o.q_eval),esc(o.hadith||''),stateBadge(o.h_eval),esc(o.matn||''),stateBadge(o.m_eval),''];}))}</div></div>`; }
function reports(v){ followupReports(v); }
function teachers(v){ if(!isAdmin()) return; v.innerHTML=`<div class="toolbar"><button class="btn" onclick="teacherForm()">إضافة مدرس</button></div><div class="table-wrap">${table(['ID','الاسم','الهاتف','إجراءات'],state.data.teachers.map(t=>[t.id,esc(t.name),esc(t.phone||''),`<button class="btn gold" onclick="teacherForm('${t.id}')">تعديل</button>`]))}</div>`; }
function teacherForm(id=''){ const t=state.data.teachers.find(x=>String(x.id)===String(id))||{}; showModal(`<h3>${id?'تعديل':'إضافة'} مدرس</h3><div class="form"><div class="field"><label>ID</label><input id="tid" value="${esc(t.id||uid())}" ${id?'readonly':''}></div><div class="field"><label>الاسم</label><input id="tname" value="${esc(t.name)}"></div><div class="field"><label>الهاتف</label><input id="tphone" value="${esc(t.phone)}"></div></div><br><button class="btn" onclick="saveTeacher('${id}')">حفظ</button>`); }
async function saveTeacher(id){ try{ await api('saveGeneric',{table:'teachers',row:{id:$('#tid').value,name:$('#tname').value,phone:$('#tphone').value}}); toast('تم الحفظ'); closeModal(); await load(); }catch(e){toast(e.message,true)} }
function halaqat(v){ if(!isAdmin()) return; v.innerHTML=`<div class="toolbar"><button class="btn" onclick="halaqaForm()">إضافة حلقة</button></div><div class="table-wrap">${table(['ID','الحلقة','الأستاذ','عدد الطلاب'],state.data.halaqat.map(h=>[h.id,esc(h.name),teacherName(h.teacher_id),state.data.students.filter(s=>String(s.halaqa_id)===String(h.id)).length]))}</div>`; }
function halaqaForm(){ showModal(`<h3>إضافة حلقة</h3><div class="form"><div class="field"><label>ID</label><input id="hid" value="${uid()}"></div><div class="field"><label>اسم الحلقة</label><input id="hname"></div><div class="field"><label>الأستاذ</label><select id="hteacher">${state.data.teachers.map(t=>`<option value="${t.id}">${esc(t.name)}</option>`)}</select></div></div><br><button class="btn" onclick="saveHalaqa()">حفظ</button>`); }
async function saveHalaqa(){ try{ await api('saveGeneric',{table:'halaqat',row:{id:$('#hid').value,name:$('#hname').value,teacher_id:$('#hteacher').value}}); closeModal(); await load(); }catch(e){toast(e.message,true)} }
function events(v){ if(!isAdmin()) return; v.innerHTML=`<div class="toolbar"><button class="btn" onclick="eventForm()">إضافة فعالية</button></div><div class="table-wrap">${table(['الفعالية','الفترة','الحالة','إجراءات'],state.data.events.map(e=>[esc(e.name),`${e.start_date} إلى ${e.end_date}`,badge(e.status||'تسجيل'),`<button class="btn secondary" onclick="eventOpen('${e.id}')">فتح</button>`]))}</div>`; }
function eventForm(){ showModal(`<h3>إضافة فعالية</h3><div class="form"><div class="field"><label>اسم الفعالية</label><input id="ename"></div><div class="field"><label>من تاريخ</label><input type="date" id="estart"></div><div class="field"><label>إلى تاريخ</label><input type="date" id="eend"></div><div class="field"><label>أسماء القراءات اليومية مفصولة بفاصلة</label><input id="eslots" value="الفجر,الظهر,العصر,المغرب,العشاء"></div></div><br><button class="btn" onclick="saveEvent()">حفظ</button>`); }
async function saveEvent(){ try{ await api('saveGeneric',{table:'events',row:{id:uid(),name:$('#ename').value,start_date:$('#estart').value,end_date:$('#eend').value,slots:$('#eslots').value,status:'تسجيل'}}); closeModal(); await load(); }catch(e){toast(e.message,true)} }
function eventOpen(id){ const e=state.data.events.find(x=>String(x.id)===String(id)); const parts=state.data.event_participants.filter(p=>String(p.event_id)===String(id)); const slots=(e.slots||'قراءة أولى').split(',').map(x=>x.trim()).filter(Boolean); showModal(`<h2>${esc(e.name)}</h2>${e.status!=='بدأت'?`<div class="card"><h3>تسجيل المشاركين</h3><input id="epq" placeholder="ID الطالب"><button class="btn" onclick="addParticipant('${id}')">إضافة مشارك</button><button class="btn gold" onclick="startEvent('${id}')">بدء الفعالية</button></div>`:''}<div class="card section"><h3>تسجيل القراءات</h3><select id="slotSel">${slots.map(s=>`<option>${esc(s)}</option>`)}</select><input id="evStudent" placeholder="ID الطالب"><button class="btn" onclick="eventManual('${id}')">تسجيل</button><button class="btn secondary" onclick="openQrScanner('event','${id}',$('#slotSel').value)">قارئ QR</button></div><h3>المشاركون</h3>${table(['ID','الاسم','نسبة الإنجاز'],parts.map(p=>{const s=state.data.students.find(x=>String(x.id)===String(p.student_id))||{};return[p.student_id,esc(s.name),eventPercent(id,p.student_id)+'%']}))}`); }
async function addParticipant(event_id){ try{ await api('saveGeneric',{table:'event_participants',row:{id:uid(),event_id,student_id:$('#epq').value.trim()}}); toast('تمت الإضافة'); await load(); eventOpen(event_id); }catch(e){toast(e.message,true)} }
async function startEvent(event_id){ try{ const e=state.data.events.find(x=>String(x.id)===String(event_id)); e.status='بدأت'; await api('saveGeneric',{table:'events',row:e}); toast('تم بدء الفعالية'); await load(); eventOpen(event_id); }catch(e){toast(e.message,true)} }
async function eventManual(event_id){ try{ await api('eventCheckin',{event_id,slot:$('#slotSel').value,student_id:$('#evStudent').value.trim(),date:today(),time:nowTime()}); toast('تم التسجيل'); await load(); eventOpen(event_id); }catch(e){toast(e.message,true)} }
function users(v){ if(!isAdmin()) return; v.innerHTML=`<div class="toolbar"><button class="btn" onclick="userForm()">إضافة مستخدم</button></div><div class="table-wrap">${table(['المستخدم','الدور','ربط مدرس','حالة'],state.data.users.map(u=>[esc(u.username),roleName(u.role),teacherName(u.teacher_id),badge(u.active!=='لا'?'نشط':'معطل')]))}</div>`; }
function userForm(){ showModal(`<h3>إضافة مستخدم</h3><div class="form"><div class="field"><label>اسم المستخدم</label><input id="un"></div><div class="field"><label>كلمة المرور</label><input id="up"></div><div class="field"><label>الدور</label><select id="ur"><option value="teacher">أستاذ</option><option value="supervisor">مشرف</option><option value="admin">إدارة</option></select></div><div class="field"><label>ربط بمدرس</label><select id="ut"><option value=""></option>${state.data.teachers.map(t=>`<option value="${t.id}">${esc(t.name)}</option>`)}</select></div></div><br><button class="btn" onclick="saveUser()">حفظ</button>`); }
async function saveUser(){ try{ await api('saveUser',{username:$('#un').value,password:$('#up').value,role:$('#ur').value,teacher_id:$('#ut').value,active:'نعم'}); closeModal(); await load(); }catch(e){toast(e.message,true)} }
function settings(v){ if(!isAdmin()) return; v.innerHTML=`<div class="card"><h3>إعدادات المؤسسة</h3><div class="form"><div class="field"><label>اسم المؤسسة</label><input id="setName" value="${esc(state.data.settings.institution_name||'')}"></div><div class="field"><label>وصف قصير</label><input id="setDesc" value="${esc(state.data.settings.description||'')}"></div><div class="field"><label>نص الختم</label><input id="setStamp" value="${esc(state.data.settings.stamp_text||'')}"></div><div class="field"><label>بداية ID</label><input id="setStart" value="${esc(state.data.settings.student_id_start||100001)}"></div><div class="field"><label>نهاية ID</label><input id="setEnd" value="${esc(state.data.settings.student_id_end||101111)}"></div><div class="field"><label>ID الطالب القادم</label><input id="setNext" value="${esc(state.data.settings.next_student_id||100001)}"></div><div class="field"><label>شعار المؤسسة</label><input id="setLogo" type="file" accept="image/*" onchange="previewLogo(this)"></div></div><br><img id="logoPreview" src="${esc(state.data.settings.logo_url||'')}" style="max-width:150px"><br><br><button class="btn" onclick="saveSettings()">حفظ الإعدادات</button></div><div class="card section"><h3>روابط النشر</h3><p>بعد رفع الواجهة على GitHub Pages، ضع الرابط هنا في إعدادات المشروع أو شاركه مع الأساتذة.</p><code>https://USERNAME.github.io/REPOSITORY/</code></div>`; }
function previewLogo(inp){ const f=inp.files[0]; if(!f)return; const r=new FileReader(); r.onload=()=>$('#logoPreview').src=r.result; r.readAsDataURL(f); }
async function saveSettings(){ try{ const settings={institution_name:$('#setName').value,description:$('#setDesc').value,stamp_text:$('#setStamp').value,student_id_start:$('#setStart').value,student_id_end:$('#setEnd').value,next_student_id:$('#setNext').value,logo_data:$('#logoPreview').src.startsWith('data:')?$('#logoPreview').src:''}; await api('saveSettings',settings); toast('تم حفظ الإعدادات'); await load(); }catch(e){toast(e.message,true)} }
function table(head, rows){return `<table class="table"><thead><tr>${head.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c??''}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
function badge(x){return `<span class="badge ${String(x).includes('غائب')?'danger':''}">${esc(x)}</span>`} function stateBadge(x){ let c=x==='إعادة'?'danger':(x==='جيد'?'warn':''); return `<span class="badge ${c}">${esc(x||'')}</span>`; }
function photo(src,s=40){return src?`<img src="${esc(src)}" style="width:${s}px;height:${s}px;object-fit:cover;border-radius:12px">`:'—'}
function halaqaName(id){return esc((state.data.halaqat.find(h=>String(h.id)===String(id))||{}).name||'')} function teacherName(id){return esc((state.data.teachers.find(t=>String(t.id)===String(id))||{}).name||'')}
function waLink(phone,text){ if(!phone) return ''; return `<a class="btn secondary" target="_blank" href="https://wa.me/${String(phone).replace(/\D/g,'')}">${text}</a>` }
function waLate(s,time){ const msg=encodeURIComponent(`السلام عليكم ورحمة الله\nإن ابنكم: ${s.name}\nجاء إلى الحلقة متأخراً في تمام الساعة: ${time}`); return s.guardian_phone?`<a class="btn secondary" target="_blank" href="https://wa.me/${String(s.guardian_phone).replace(/\D/g,'')}?text=${msg}">واتساب</a>`:''; }
async function delRow(table,id){ if(!confirm('تأكيد الحذف؟'))return; try{await api('deleteRow',{table,id});toast('تم الحذف');await load();}catch(e){toast(e.message,true)} }
function showModal(html){ let m=$('.modal'); if(!m){m=document.createElement('div');m.className='modal';document.body.appendChild(m)} m.innerHTML=`<div class="modal-box"><button class="close" onclick="closeModal()">×</button>${html}</div>`; m.classList.add('show'); m.onclick=e=>{if(e.target===m)closeModal()}; return m; } function closeModal(){ $('.modal')?.classList.remove('show'); stopQr(); } document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
function qrCard(id){ const s=state.data.students.find(x=>String(x.id)===String(id)); showModal(`<h2>بطاقة QR</h2><div style="text-align:center"><div id="qrPrint" style="display:inline-block;padding:20px;border:1px solid #ddd;border-radius:18px"><h3>${esc(s.name)}</h3><p>ID: ${esc(s.id)}</p><img src="https://api.qrserver.com/v1/create-qr-code/?size=180x180&data=STUDENT:${encodeURIComponent(s.id)}"><p>${esc(state.data.settings.institution_name||'')}</p></div><br><button class="btn" onclick="window.print()">طباعة</button></div>`); }
function eventPercent(event_id,student_id){ const e=state.data.events.find(x=>String(x.id)===String(event_id)); if(!e)return 0; const slots=(e.slots||'').split(',').filter(Boolean).length||1; const days=Math.max(1,Math.round((new Date(e.end_date)-new Date(e.start_date))/(86400000))+1||1); const total=slots*days; const done=new Set(state.data.event_attendance.filter(a=>String(a.event_id)===String(event_id)&&String(a.student_id)===String(student_id)).map(a=>a.date+'|'+a.slot)).size; return Math.min(100,Math.round(done*100/total)); }
function eventResultsFor(student_id){ return state.data.event_participants.filter(p=>String(p.student_id)===String(student_id)).map(p=>{const e=state.data.events.find(x=>String(x.id)===String(p.event_id))||{};return {name:e.name||'',percent:eventPercent(p.event_id,student_id)}}); }
boot();
